name: Selenide Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Run Selenide Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Installed ChromeDriver Version
      id: check_chromedriver_version
      run: |
        INSTALLED_CHROMEDRIVER_VERSION=$(chromedriver --version | cut -d' ' -f2 | cut -d'.' -f1)
        RECOMMENDED_CHROMEDRIVER_VERSION=$(google-chrome --version | cut -d' ' -f3 | cut -d'.' -f1)
        if [ "$INSTALLED_CHROMEDRIVER_VERSION" == "$RECOMMENDED_CHROMEDRIVER_VERSION" ]; then
          echo "ChromeDriver version is up to date. Skipping installation."
          echo "::set-output name=install_chromedriver::false"
        else
          echo "ChromeDriver version needs update. Proceeding with installation."
          echo "::set-output name=install_chromedriver::true"
        fi

    - name: Install ChromeDriver
      if: steps.check_chromedriver_version.outputs.install_chromedriver == 'true'
      run: |
        echo "Downloading ChromeDriver..."
        CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3 | cut -d'.' -f1)
        echo "Detected Chrome version: $CHROME_VERSION"
        CHROMEDRIVER_VERSION=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        echo "Unzipping ChromeDriver..."
        unzip chromedriver_linux64.zip
        echo "Setting permissions..."
        chmod +x chromedriver
        echo "Moving ChromeDriver to /usr/local/bin/..."
        sudo mv chromedriver /usr/local/bin/

    - name: Run Selenide Tests
      run: |
        pytest --alluredir=$GITHUB_WORKSPACE/results/allure-report $GITHUB_WORKSPACE/test/ -m gui_tests

    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: $GITHUB_WORKSPACE/results/allure-report
