name: Selenide Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Selenide Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt file with Selenide and other dependencies

    - name: Run Selenide Tests
      run: |
        pytest --alluredir=$GITHUB_WORKSPACE/results/allure-report $GITHUB_WORKSPACE/test/ -m gui_tests

    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: $GITHUB_WORKSPACE/results/allure-report
